name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest # This will be replaced by the on-premise runner label if available
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Use a specific Node.js version

    - name: Install dependencies
      run: npm install

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://localhost:9000
      with:
        projectBaseDir: . # Adjust if your project is in a subdirectory

    - name: Run in development environment
      run: npm run dev
